import type { Config } from "tailwindcss";

export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        background: "#fbf9f1",
        surface: "#fbf9f1",
        "surface-dim": "#dcdad2",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f5f4ec",
        "surface-container": "#f0eee6",
        "surface-container-high": "#eae8e0",
        "surface-container-highest": "#e4e3db",
        "on-surface": "#1b1c17",
        "on-surface-variant": "#504442",
        "inverse-surface": "#30312c",
        "inverse-on-surface": "#f3f1e9",
        outline: "#827472",
        "outline-variant": "#d3c3c0",
        primary: "#271310",
        "on-primary": "#ffffff",
        "primary-container": "#3e2723",
        "on-primary-container": "#ae8d87",
        "inverse-primary": "#e3beb8",
        secondary: "#6f5a52",
        "on-secondary": "#ffffff",
        "secondary-container": "#fadcd2",
        "on-secondary-container": "#766057",
        tertiary: "#231600",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#3d2a00",
        "on-tertiary-container": "#b38f4a",
        "tertiary-fixed": "#ffdea5",
        "tertiary-fixed-dim": "#e9c176",
        "on-tertiary-fixed": "#261900",
      },
      fontFamily: {
        display: ["Playfair Display", "Georgia", "serif"],
        sans: ["Inter", "ui-sans-serif", "system-ui", "sans-serif"],
      },
      boxShadow: {
        soft: "0 24px 70px rgba(39, 19, 16, 0.14)",
        lift: "0 18px 42px rgba(62, 39, 35, 0.18)",
      },
    },
  },
  plugins: [],
} satisfies Config;
